- .github/workflows/go.yml
- OAPI-generator.md
- Readme.md
- main.go
- main_test.go
- src/adyen/api.go
- src/adyen/api_test.go
- tests/binlookup_test.go
- tests/checkout_test.go
- tests/checkoututility_test.go
- tests/notification_handler_test.go
- tests/payment_test.go
- tests/payouts_test.go
- tests/recurring_test.go
> Refactor main entry package name

- .github/workflows/go.yml
- src/hmacvalidator/hmacvalidator.go
- src/hmacvalidator/hmacvalidator_test.go
> Adds HMAC Validator

- src/checkout/model_checkout_payments_action.go
- src/checkout/model_sdkdata.go
Describe the changes proposed in this pull request:
https://docs.adyen.com/payment-methods/paypal/web-component#-payments-response
Need an sdkData object to be returned
Getting proper response for Paypal smart overlay
**Fixed issue**: [DOC-4563]
> Support Paypal smart overlay in payment action response object

- src/common/configuration.go
> fix lib version

- src/adyen/api.go
- src/common/client.go
- tests/checkout_test.go
> Add support to idempotency key

- src/checkout/api_default.go
- src/checkout/model_checkout_balance_check_request.go
- src/common/client.go
- tests/checkout_test.go
> adds support for other HTTP methods

- src/checkout/model_payment_response.go
- tests/checkout_test.go
see #93
There are tests
**Fixed issue**:  #93
> Fixes nil actions in payment response #93

- Readme.md
Update Readme.md with the new template
> Update Readme.md with the new template

- .github/CODEOWNERS
Please include myself so I can help with managing/maintaining the repo
> Update CODEOWNERS: add Beppe

- src/notification/notification_handler.go
Fix: typo in notifications event codes
**Fixed issue**:
> fix: typo in notifications

- src/adyen/api.go
This PR should fix an issue #153
> bump Checkout API version to v69

- src/common/configuration.go
Update library version (v6.0.1) for new release
> Update library version v6.0.1

- RELEASE_PROCESS.md
- src/adyen/api.go
- src/checkout/api_modifications.go
- src/common/configuration.go
- src/notification/model_notification.go
- tests/api_modifications_test.go
Merge `develop` into `main` and release v6.0.1
> Release v6.0.1

- src/legalentity/configuration.go
PR to correct the `live` url for LEM API
> Correct live url for LEM

- src/common/client.go
Sends application info via dedicated headers.
> ITT-38: Application info via headers

- .github/workflows/models.yml
Fixes the error: 
```
[main] ERROR o.o.c.languages.AbstractGoCodegen - Error running the command (/bin/goimports -w /home/runner/work/adyen-go-api-library/adyen-go-api-library/src/balanceplatform/model_account_holder_info.go). Exception: Cannot run program "/bin/goimports": error=2, No such file or directory
```
> Setup Go for model formatting

- .github/workflows/codeql-analysis.yml
- .github/workflows/gh_release.yml
- .github/workflows/go.yml
- .github/workflows/models.yml
- .github/workflows/release_request.yml
- Makefile
These workflows assist us on publishing new releases.
> ITT-534: Release automation

- .github/workflows/gh_release.yml
- .github/workflows/release_request.yml
Release automation is moving to Node.
> Node release automation

- .github/workflows/format.yml
- Makefile
Formats code generated by https://github.com/adyen/adyen-sdk-automation/.
> Auto format workflow

- .github/workflows/format.yml
Conditional starting with "not" (`!`) must be escaped.
> Negation fix

- Readme.md
This PR adds a section on unmarshalling JSON Strings to the readme
> add section on unmarshalling JSON Strings to readme

- tests/recurring_test.go
The server no longer returns a `500` response for cases like the one from this test. 
* unit
* integration
> Update recurring test due to http status change

- Readme.md
- tests/checkout/integration_test.go
Added Issuer setter to integration test to pass Issuer string without breaking integration_test.go. 
Tested with Test Merchant account.
> added SetIssuer to test

- src/adyen/api.go
- src/common/configuration.go
> Add payments app api base url

- .github/workflows/go.yml
This PR runs the Go workflow (Build & Verify) when a PR is merged
> Run Go workflow upon merge

- .github/workflows/format.yml
Clean the `Format` workflow removing/editing logs
> Format Workflow: update logging

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
**Description**
This PR adds .yml bug report and feature request form that is structured to collect all essential details upfront.
Read more [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms).
> Add GitHub issue forms

- src/acswebhook/model_authentication_decision.go
- src/acswebhook/model_purchase.go
- src/acswebhook/model_relayed_authentication_request.go
- src/acswebhook/model_relayed_authentication_response.go
- src/acswebhook/model_service_error.go
- src/checkout/model_pix_details.go
- src/checkout/model_pix_recurring.go
- src/management/model_affirm_info.go
- src/management/model_pay_to_info.go
- src/transfers/model_lodging.go
- src/transferwebhook/model_lodging.go
This pr updates the recent service update imports to v20
> update imports to v20

- tests/checkout/integration_test.go
This test checks if field Reference is provided but needs valid merchant account. Added body without Reference.
> Refactor checkout session test

- tests/model_payment_request_test.go
Add test to verify JSON serialisation (i.e. attributes with default value are not included)
> Add test for JSON serialisation

- .github/workflows/format.yml
Run `format` action on all `sdk-automation/**` branches
> Format action configuration
