Adyen/adyen-go-api-library

src/hmacvalidator/hmacvalidator.go
src/hmacvalidator/hmacvalidator_test.go

Key had wrong capitalization:
https://docs.adyen.com/development-resources/webhooks/verify-hmac-signatures#enable-hmac-signatures

Fix key for hmac signature

---

src/checkout/model_payment_request.go
src/checkout/model_payment_response.go
tests/model_payment_request_test.go

Case fallthrough works a bit differently in Golang, this should fix the bug introduced in last release

fix case fallthrough bug

---

src/checkout/model_payment_request.go
tests/model_payment_request_test.go

As raised in #133 the developer is incurring the following problem
> We want to make storing payment methods optional. When we try to pass false value into this struct it omits by default that's why it always saves the card.
This is going to be addressed in the Adyen (backend) platform (when `false` or missing the payment methods shall not be stored), meanwhile we can address this in the Go SDK
Verified the payload sent to the Adyen (backend) platform, it contains now `storePaymentMethod:false`
**Fixed issue**:  
Fix #133

Remove omitempty to retain default value (false)

---

src/notification/model_notification.go

When notification webhook receives an empty http body, Notification.GetNotificationItems causes panic
This PR adds check of nil pointer on NotificationItems
**Fixed issue**:

fix panic when NotificationItems is nil

---

RELEASE_PROCESS.md

Add step to remind  the update of the API version (this is to avoid problems like in #153) which is supported
Not applicable

Add new step (update API version)

---

src/checkout/api_modifications.go
tests/api_modifications_test.go

The API modification endpoint is incorrectly built using the `paymentPspReference` string rather than the value of the variable (path parameter).
This PR addresses this problem and creates unit testing (for the failing scenarios) which were missing.
Verify endpoint URL is built correctly and the client request reaches the Adyen backend
**Fixed issue**: 
Fix #155

PaymentPspReference hardcoded in endpoint URL

---

.github/dependabot.yml

This PR removes Dependabot configuration (we have already enabled Renovate bot)
Delete dependabot config file
N/A

Delete dependabot configuration file

---

Makefile

Fixes the following error: 
```
> Run make models
git clone https://github.com/Adyen/adyen-openapi.git schema
Cloning into 'schema'...
perl -i -pe 's/"openapi" : "3.[0-9].[0-9]"/"openapi" : "3.0.0"/' schema/json/*.json
wget --quiet -o /dev/null https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/6.[4](https://github.com/Adyen/adyen-go-api-library/actions/runs/4676757372/jobs/8283451736#step:3:5).0/openapi-generator-cli-[6](https://github.com/Adyen/adyen-go-api-library/actions/runs/4676757372/jobs/8283451736#step:3:7).4.0.jar -O bin/openapi-generator-cli.jar
bin/openapi-generator-cli.jar: No such file or directory
make: *** [Makefile:64: bin/openapi-generator-cli.jar] Error 1
```
https://github.com/Adyen/adyen-go-api-library/actions/runs/4676757372/jobs/8283451736#step:3:9 …

Fix models workflow

---

Makefile

Fixes the following error: 
```
> Run make models
git clone https://github.com/Adyen/adyen-openapi.git schema
Cloning into 'schema'...
perl -i -pe 's/"openapi" : "3.[0-9].[0-9]"/"openapi" : "3.0.0"/' schema/json/*.json
wget --quiet -o /dev/null https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/6.[4](https://github.com/Adyen/adyen-go-api-library/actions/runs/4676757372/jobs/8283451736#step:3:5).0/openapi-generator-cli-[6](https://github.com/Adyen/adyen-go-api-library/actions/runs/4676757372/jobs/8283451736#step:3:7).4.0.jar -O bin/openapi-generator-cli.jar
bin/openapi-generator-cli.jar: No such file or directory
make: *** [Makefile:64: bin/openapi-generator-cli.jar] Error 1
```
https://github.com/Adyen/adyen-go-api-library/actions/runs/4676757372/jobs/8283451736#step:3:9 …

[redo] Fix models workflow

---

src/common/client.go

Mask authentication headers from debug logs. 
Fixes #244

Mask credentials from debug logs

---

templates/custom/model_simple.mustache

OAS type nullable string with default breaks a certain mustache type. We don't need this type as go handles var assignment without type fine.

adjust template and remove unnecessary type for default

---

.github/workflows/label_new_issues.yml
.github/workflows/stale.yml

Added new issue labeler which labels new issues with 'needs response'
Added Stalebot which ignores 'needs response' and 'do not stale'
Tested in a fork of the Python library with and without 'needs response' label

added new issue labeler and stalebot 

---

.github/workflows/stale.yml

updated stale.yml to ignore pull requests.
unset the default checks by setting them to -1 only consider pr's with the labels 'awaiting-changes', 'blocked', 'work-in-progress', 'awaiting-upstream'. removing the pr label when updated

fix stalebot

---

tests/checkout/integration_test.go

checkout/integration test was failing because Issuer is no longer required and setter is removed.
[src/checkout/model_ideal_details.go](https://github.com/Adyen/adyen-go-api-library/pull/342/files#diff-ba35d55e88aad387be5735dde8ab4a8099294170d6c9dc42227ae618cb656a23)
[src/checkout/model_ideal_donations.go](https://github.com/Adyen/adyen-go-api-library/pull/342/files#diff-cfdd899069fbd01041b4b1973f412065823db1bc3a04b0c4dfcb9c9f32fedb82)
adjusted the test and want to merge into sdk-automation to see if this will solve the issue

removed issuer string from NewIdealDetails

---

templates/custom/api.mustache
templates/custom/model_simple.mustache

The library deprecates correctly the attributes/endpoints that are marked as deprecated in the OpenAPI spec files.  
This PR improves the existing code by adding the additional information (`deprecatedInVersion`, `deprecatedMessage`) in the comments.

Improve deprecation information adding deprecatedInVersion and deprecatedMessage in the comments 

---

.github/workflows/codeql-analysis.yml

**Description**
CodeQL workflows runs on `push`, `pull_request` and `cron`.
This PR updates the workflow configuration to run on `cron` only.

Run CodeQL analysis on cron job only

---

tests/checkout/integration_test.go

iDEAL2 no longer requires the issuer parameter. This PR removes the hardcoded issuer from the test to implement the iDEAL2 flow.

Remove Issuer from iDEAL Test for iDEAL2 Compatibility

---

.github/workflows/stale.yml

This PR updates the stale issue workflow by adding the close-issue-label flag. Previously, when issues were closed due to inactivity, they were automatically marked as "closed as not planned", which was misleading. Now, a custom label is applied when an issue is closed due to inactivity.
Testing:
* Forked the repository to test the changes.
* Modified the workflow to run more frequently and reduced stale/close time.
Verified that:
* Issues were correctly marked as stale.
* Issues were closed with the new label "closed-due-to-inactivity" instead of the default label.

Add close-issue-label flag to correctly label closed issues 

---

src/hmacvalidator/hmacvalidator.go
src/hmacvalidator/hmacvalidator_test.go

This pull request adds a check to ensure that AdditionalData is not nil before it is used. This prevents a panic when AdditionalData is nil in the ValidateHmac function. If AdditionalData is nil, the function now returns false.

Add nil-check for AdditionalData in ValidateHmac

---

.github/workflows/go.yml
.github/workflows/sonarcloud.yml
sonar-project.properties

- Improved the workflow to two main jobs:
1. `go-test`: Runs unit tests across multiple Go versions (1.13, 1.17, 1.21)
2. `release-integration-test`: Runs integration tests only for release PRs from the main repository
- Removed environment variables from unit tests since they should be self-contained
- Kept environment variables only in the integration test job where they are needed
- Added a CI based Sonarcloud to allow easy customizations
- Better separation of concerns between unit and integration tests
- Improved security by not exposing sensitive credentials to forked PRs
- Clearer workflow structure with focused jobs
- The updated workflow ran successfully in my forked branch

Improve GitHub workflow

---

src/adyen/api.go
tests/readme_test.go

This PR sets the HTTP Client default timeout (to 60 seconds) in case it is not defined in the `common.Config` object.
Note that the default timeout is only set when the library creates the http.Client` instance.

Default timeout for the HTTP client

---

.github/workflows/go.yml

Update CI workflow to:
- run `on push` only on `main` branch (when a PR is merged)
- run `on pull_request` on `main`, SDK Automation Bot PRs and Release bumps

CI workflow: update to avoid unnecessary executions
